### ISSUE TITLE
Darle algo de estilos e integación con la página a las vizzs del Scanner

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#10]
Que tengan espaciados entre elementos haciendo uso del tipi-uikit y que las tipografías sean heredadas de la página (quizá en algunos casos a un tamaño algo mayor para que quede más integrado).

**Comment by Saigesp** [comment]
Done with 87b70204712a2390e5ec90fba7f9a4f8cd406b59
