### ISSUE TITLE
Modoficaciones en el Sunburst del Scanner

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#12]
* Mostramos siempre el tooltip
* En el arco de los ODS, hacer la propuesta sugerida (_Puedo meter (creo es mejor) el propio texto del aŕea (topic, subtopic o tag) dentro del propio área (ocultando los que no quepan, pero mostrándolos si se expanden)_)
* Que la animación del Sunburst vaya algo más lenta para que de tiempo a verla

**Comment by pr3ssh** [comment]
@Saigesp  He actualizado la descripción para que sea reflejo del estado de la cuestión.

**Comment by Saigesp** [comment]
Done with https://github.com/politicalwatch/tipi-uikit/pull/14
