### ISSUE TITLE
Meter una leyenda de los ODS que han aparecido en el Scanner

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#13]
Como se muestra mucha veces el formato reducido del ODS y el color de cada uno, mostrar entre el mensaje _Aquí tienes una una relación visual de tu texto, para que de un primer vistazo veas conexiones interesantes._ y el inicio de las visualizaciones un bloque como minivisualización en el que se indiquen los colores y nombres largos de los ODS que hayan aparecido (y que por ende nos encontraremos en la página). Si te parece, por si se te ocurre algo, podemos usar además las imágenes en SVG de los ODS que hayan salido (los ficheros están en el archivo de configuración como los colores).

**Comment by Saigesp** [comment]
Done with 91531ac862ee383cf4f7f7efd2fb5d96e4e4bbf1
