### ISSUE TITLE
Modificar funcionamiento del BarChart

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#15]
Arriba del Barchart siempre se mostrará un selector con posibles documentos. Si no tienes seleccionado ninguno, el Barchart es el del texto que estás escaneando. Si lo seleccionas, el Barchart pasa a comparar los dos textos.

**Comment by Saigesp** [comment]
Done with 88275b2c93093dce7913ea2781ef57976d988faf
