### ISSUE TITLE
Introducir la tabla al final de la página Scanner

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#16]
**Pero con los estilos de tabla que están en el [uikit](https://tipiui-docs.netlify.com/base)**

![Esquema-Resumido](https://user-images.githubusercontent.com/404339/77639985-eac87680-6f59-11ea-81fc-046c6b4e8f48.png)

**Comment by Saigesp** [comment]
Subido en 4d31e1a4709a70a7ab53c43824943a69fe97cbe0

Pongo los controles de la tabla (ordenar, buscar...)? Si es así, los estilos están definidos en algún sitio?
