### ISSUE TITLE
El color del texto del placeholder y del valor en los campos del buscador es el mismo y eso confunde un poco

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#21]
Podemos comentarlo con Rubén.

**Comment by dacmail** [comment]
Te refieres a los selects, no? Por que en los campos de texto sí  es distinto. Ya está modificado en tipi-ui-kit

**Comment by pr3ssh** [comment]
Genial. Creo que faltan los de fecha.

**Comment by dacmail** [comment]
Ya debería estar todo en tipi-uiokit
