### ISSUE TITLE
Que todas las peticiones incorrectas redirijan a la página 404

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#3]
Se puede dar el caso que al acceder a topic, deputy, parliamentarygroup e initiative el id no sea correcto por lo que se queda la vista cargada o una página en blanco. Si esto ocurre, habría que redireccionar a la [Page404](https://github.com/politicalwatch/parlamento2030.es/blob/master/src/router/index.js#L134).

**Comment by dacmail** [comment]
Fixed in 93726f8
