### ISSUE TITLE
Mostrar en la ficha de grupos parlamentarios el listado de diputados y diputadas

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#4]
No sé si mostrarlo junto con las últimas iniciativas, con tabs, como veas mejor.

**Comment by dacmail** [comment]
@pr3ssh había algun sitio donde consultar la documentación de la api? Para ver cómo puedo traer diputados de un grupo concreto

**Comment by pr3ssh** [comment]
No puedes con los métodos que tiene la API ahora. Creo que la opción más
rápida es hacer un filter de todos los diputados.

Pablo Martín
Director tecnológico
@pr3ssh

**Comment by dacmail** [comment]
Ok así lo haré

**Comment by pr3ssh** [comment]
Además como ya están todos cargados en estado pues es lo más rápido 😅

Pablo Martín
Director tecnológico
@pr3ssh

**Comment by dacmail** [comment]
Ok, ya los muestro, he reutilizado el mismo componente de las iniciativas, pero los muestro uno al lado del otro en 3 columnas para que ocupen menos, me parecía mejor esta solución que usar tabs. Si está ok la cierras y si no me dices.

**Comment by pr3ssh** [comment]
Genial @dacmail. La dejamos así y meto en Asana la modificación para que se
tenga en cuenta.

Pablo Martín
Director tecnológico
@pr3ssh

**Comment by dacmail** [comment]
Cierro pues!
