### ISSUE TITLE
Error módulos ES

### ISSUE THREAD

**Issue by serman** [politicalwatch/parlamento2030.es#47]
Hola!
Al arrancar el proyecto con 
```
npm run dev

> parlamento2030.es@0.1.0 dev
> vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.2  ready in 447 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
(node:72165) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /Users/sergiogalan/proyectos/politicalwatch/parlamento2030.es): [SyntaxError] Unexpected token 'export'
/Users/sergiogalan/proyectos/politicalwatch/parlamento2030.es/.postcssrc.js:1
export default {
```

El arreglo es:  poner   "type": "module", en el package.json pero no quiero hacer cambios que no me correspondan.

¿No os da ese error a vosotros? Igual es tema mio de dependencias. Mi versión de node es: v18.12.1

**Comment by alex-ahumada** [comment]
Buenas @serman !
Ese error está corregido en https://github.com/politicalwatch/parlamento2030.es/commit/c881dcc599768db56d5cb56f9d9ac57184324802 que publicamos hace un rato, ¡gracias por el aviso!

**Comment by serman** [comment]
ah ok, disculpa no lo había visto y estaba con el código que descargué ayer. Esto si que es velocidad!.

Gracias!

**Comment by alex-ahumada** [comment]
Issue autosolucionable, ¡de las mejores!
