### ISSUE TITLE
Si se hace una búsqueda por diputado/a, mostrar un acceso a la ficha de ese/a diputado/a

### ISSUE THREAD

**Issue by pr3ssh** [politicalwatch/parlamento2030.es#6]
Que el acceso sea un bloque previo a los resultados de la búsqueda.

**Comment by dacmail** [comment]
@pr3ssh Entiendo que es solo cuando se hace una búsqueda exclusivamente por el diputado y no cuando se combina con otros parámetros, no?

**Comment by pr3ssh** [comment]
Yo lo haría en cualquier caso, siempre que se busque al menos por diputado.
Al menos al principio para que la gente lo vaya entendiendo y accediendo a
dichas páginas.

Pablo Martín
Director tecnológico
@pr3ssh

**Comment by dacmail** [comment]
OK!

**Comment by dacmail** [comment]
@pr3ssh He implementado una primera aproximación de esto, se muestra como un párrafo justo encima de los resultados de búsqueda.

Si te fijas, una vez has ejecutado la primera búsqueda, cuando cambias de autor o diputado en el formulario, se actualiza automáticamente el texto y enlace. Si no quieres que pase esto y que solo se cambie al volver a realizar la búsqueda, tendría que cambiar ciertas cosas, por ahora he preferido coger la vía más rápida y si quieres que lo mejore me dices.

Si no, puedes cerrar estas issues

**Comment by pr3ssh** [comment]
Si te parece lo que podemos hacer, ya que está vinculado al modelo, es mostrar dicho bloque cuando se seleccione un diputado (incluso antes de buscar). Y cuando cambie en el formulario pues se actualiza. Te parece?
